# MD004/ul-style
MD004: false

# MD007/ul-indent
MD007: false

# MD013/line-length
MD013: false

# MD014/commands-show-output
MD014: false

# MD024/no-duplicate-heading/no-duplicate-header
MD024: false

# MD025/single-title/single-h1
MD025: false

# MD026/no-trailing-punctuation
MD026: false

# MD029/ol-prefix Ordered list item prefix
MD029: false

# MD030/list-marker-space
MD030: false

# MD033/no-inline-html
MD033: false

# MD034/no-bare-urls Bare URL used
MD034: false

# MD035/hr-style
MD035: false

# MD037/no-space-in-emphasis
MD037: false

# MD041/first-line-heading/first-line-h1
MD041: false

# MD042/no-empty-links
MD042: false

# MD046/code-block-style
MD046: false
