name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Navigate to repo
        run: cd $GITHUB_WORKSPACE
      - name: "[cache] .cache"
        uses: actions/cache@master
        with:
          key: gatsby-cache-folder
          path: .cache
      - name: "[cache] public"
        uses: actions/cache@master
        with:
          key: gatsby-public-folder
          path: public
      - uses: actions/setup-node@v1
        with:
          node-version: "14.2.0"
      - name: Install deps
        run: npm install
      - name: Build project
        run: npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_PRODUCTION_API_TOKEN }}
          environment: "production"
