name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1
      with:
        node-version: '14.2.0'
    - name: Install deps
      run: npm install
    - name: Install Wrangler
      run: npm i @cloudflare/wrangler -g
    - name: Install Workers script deps
      run: npm install
    - name: Build project
      run: npm run build
    - name: Wrangler auth check
      run: wrangler whoami
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
    - name: Upload assets
      run: wrangler publish
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_EMAIL: ${{ secrets.CF_EMAIL }}
